export const ROOSEVELT_VISUAL_TARGET = {
  source: 'approved mockup-guided noir isometric asset pass',
  principles: [
    'world should fill most of the investigation viewport at initial load',
    'visible room floor is broader than the navigation-only Walkable mask',
    'walls should read as full-height cutaway architecture rather than low borders',
    'wall material follows the approved mockup: graphite-blue upper wall, dark wood wainscot and warm brass trim',
    'walls must share the exact 2:1 isometric projection of the floor; upright pasted rectangles are forbidden',
    'internal room partitions should remain legible without turning public/service spaces into a maze',
    'Room 307, elevators, reception, CCTV and laundry should be visually recognizable without labels',
    'Room 307 must be integrated into a wall module rather than floating as a freestanding front-facing sprite',
    'characters and props must stay legible at the default camera zoom',
    'warm wall sconces and local pools of light must break up the dark architecture',
    'camera supports free pan/zoom and F to follow the detective',
  ],
  initialZoom: 0.84,
  zoomByMap: {
    'roosevelt-lobby': 0.88,
    'roosevelt-floor-3': 0.84,
    'roosevelt-basement': 0.86,
  },
  cameraPadding: { x: 165, y: 160 },
  cameraBiasByMap: {
    'roosevelt-lobby': { x: 0, y: 12 },
    'roosevelt-floor-3': { x: 0, y: 22 },
    'roosevelt-basement': { x: 0, y: 26 },
  },
  wallHeight: 158,
  internalWallHeight: 144,
  minimumWallHeight: 132,
  sconceCadence: 3,
  characterDisplay: { playerWidth: 96, playerHeight: 146, witnessWidth: 94, witnessHeight: 144 },
  // Retained for compatibility with older visual-contract tests. Structural walls are no longer stretched images.
  wallDisplay: { width: 128, height: 208 },
  internalWallDisplay: { width: 128, height: 190 },
} as const;

export type RooseveltVisualArea = {
  id: string;
  x: number;
  y: number;
  width: number;
  height: number;
};

// These footprints are rendering-only reconstructions of rooms/public spaces visible
// around the navigation corridors. They deliberately do not change Walkable/pathfinding.
export const ROOSEVELT_VISUAL_AREAS = {
  'roosevelt-lobby': [
    { id: 'lounge-wing', x: 1, y: 9, width: 7, height: 7 },
    { id: 'main-office', x: 4, y: 9, width: 5, height: 5 },
    { id: 'main-lobby', x: 6, y: 9, width: 9, height: 8 },
    { id: 'palm-room', x: 13, y: 9, width: 6, height: 7 },
    { id: 'main-kitchen', x: 7, y: 4, width: 6, height: 6 },
    { id: 'main-dining', x: 12, y: 4, width: 7, height: 6 },
  ],
  // Floor 3 is generated by rotating the canonical 20x20 topology 180 degrees for visual composition.
  // These rendering-only footprints are the same canonical areas transformed by x'=20-(x+w), y'=20-(y+h).
  'roosevelt-floor-3': [
    { id: 'west-guest-rooms', x: 12, y: 12, width: 7, height: 6 },
    { id: 'north-elevator-lobby', x: 8, y: 13, width: 4, height: 5 },
    { id: 'central-service-core', x: 7, y: 8, width: 7, height: 6 },
    { id: 'east-guest-rooms', x: 1, y: 12, width: 7, height: 6 },
    { id: 'west-lower-rooms', x: 12, y: 3, width: 7, height: 6 },
    { id: 'south-guest-landing', x: 7, y: 3, width: 5, height: 5 },
    { id: 'room-307-suite', x: 1, y: 2, width: 6, height: 7 },
  ],
  'roosevelt-basement': [
    { id: 'service-west', x: 2, y: 2, width: 8, height: 8 },
    { id: 'incinerator', x: 5, y: 4, width: 5, height: 4 },
    { id: 'fan-room', x: 9, y: 3, width: 6, height: 5 },
    { id: 'utility-core', x: 12, y: 2, width: 7, height: 5 },
    { id: 'laundry', x: 13, y: 6, width: 9, height: 6 },
  ],
} as const satisfies Record<string, readonly RooseveltVisualArea[]>;

export const ROOSEVELT_PARTITION_AREA_IDS = {
  // The reception remains open, while the lounge/Palm Room create the same readable public-space
  // framing as the approved mockup instead of one oversized empty lobby floor.
  'roosevelt-lobby': ['lounge-wing', 'main-office', 'palm-room', 'main-kitchen'],
  // The approved mockup reads as one long luxury corridor: the central core and lower landing
  // stay visually open while the two guest wings and the Room 307 suite keep strong cutaway walls.
  'roosevelt-floor-3': ['west-guest-rooms', 'east-guest-rooms', 'room-307-suite'],
  // Basement keeps the service aisle open but gives the incinerator/utility/laundry distinct rooms.
  'roosevelt-basement': ['incinerator', 'utility-core', 'laundry'],
} as const satisfies Record<string, readonly string[]>;
